name: Bug Report
description: Report a bug or unexpected behavior
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the form below.

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of what the bug is.
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: What should have happened...
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: What actually happened...
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Configure module with...
        2. Run terraform apply...
        3. See error...
    validations:
      required: true

  - type: textarea
    id: config
    attributes:
      label: Terraform Configuration
      description: Please provide the relevant Terraform configuration.
      render: hcl
      placeholder: |
        module "keycloak" {
          source = "nihldev/keycloak/aws"
          # ...
        }
    validations:
      required: false

  - type: input
    id: terraform-version
    attributes:
      label: Terraform Version
      description: Output of `terraform version`
      placeholder: "1.14.0"
    validations:
      required: true

  - type: input
    id: module-version
    attributes:
      label: Module Version
      description: Version of this module you're using
      placeholder: "0.1.0"
    validations:
      required: true

  - type: dropdown
    id: database-type
    attributes:
      label: Database Type
      description: Which database configuration are you using?
      options:
        - RDS PostgreSQL
        - Aurora Provisioned
        - Aurora Serverless v2
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Relevant Logs
      description: Please include any relevant log output or error messages.
      render: shell
    validations:
      required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I have searched existing issues to ensure this bug hasn't been reported
          required: true
        - label: I have verified this issue exists on the latest version of the module
          required: true
