name: Feature Request
description: Suggest a new feature or enhancement
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please fill out the form below.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Describe it.
      placeholder: I'm always frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see.
      placeholder: I would like the module to...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe any alternative solutions or features you've considered.
      placeholder: I also considered...
    validations:
      required: false

  - type: textarea
    id: config
    attributes:
      label: Example Configuration
      description: If applicable, provide an example of how you'd use this feature.
      render: hcl
      placeholder: |
        module "keycloak" {
          source = "nihldev/keycloak/aws"
          # new feature usage...
        }
    validations:
      required: false

  - type: dropdown
    id: impact
    attributes:
      label: Impact Area
      description: Which area of the module does this affect?
      multiple: true
      options:
        - ECS/Fargate
        - Database (RDS/Aurora)
        - Networking (ALB/Security Groups)
        - IAM/Security
        - Monitoring (CloudWatch)
        - Email (SES)
        - ECR
        - Documentation
        - Examples
        - Other
    validations:
      required: true

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I have searched existing issues to ensure this feature hasn't been requested
          required: true
        - label: I am willing to submit a PR to implement this feature
          required: false
