name: Question
description: Ask a question about using the module
labels: ["question"]
body:
  - type: markdown
    attributes:
      value: |
        Have a question? We're happy to help! Please note that GitHub Discussions may be a better place for general questions.

  - type: textarea
    id: question
    attributes:
      label: Question
      description: What would you like to know?
      placeholder: How do I...
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Context
      description: Provide any relevant context about your use case.
      placeholder: I'm trying to deploy Keycloak with...
    validations:
      required: false

  - type: textarea
    id: config
    attributes:
      label: Current Configuration
      description: If applicable, share your current configuration.
      render: hcl
    validations:
      required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I have checked the module README and examples
          required: true
        - label: I have searched existing issues and discussions
          required: true
